apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: snd-metasync
patches:
  - target:
      kind: HTTPRoute
      name: hello-world-py
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "snd-hello-world-py.apps.metasync.cc"
  - path: configmap.yaml
# Explicitly defining images allows Kustomize to override the tag
# This is often used by CI/CD pipelines (e.g., `kustomize edit set image ...`)
images:
  - name: quay.io/luban-ci/luban-hello-world-py
    newTag: latest
  - name: harbor.luban.metasync.cc/metasync/hello-world-py
    newTag: 96166cbcb9289a7b77659d8d6f55fbd6d3f994c6
